version: '3.8'

services:
  api-libros:
    build: ./Pregunta1
    ports:
      - "8000:8000"
    restart: always

  api-usuarios:
    build: ./Pregunta3
    ports:
      - "8001:8001"
    restart: always

  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: mydatabase  
      POSTGRES_USER: myuser   
      POSTGRES_PASSWORD: mypassword  
    ports:
      - "5432:5432"  
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  
    restart: always
